import 'package:flutter/material.dart';

class AppColors{
  static const Color purpleColor = Color(0xff905689);
  static const Color lightCyanColor = Color(0xffE6F1EF);
  static const Color lightWhiteColor = Color(0xfffcfbf7);
  static const Color orangeColor = Color(0xffFF671D);
  static const Color pinkColor = Color(0xffFFD4C0);
  static const Color redColor = Color(0xffFF3B30);
  static const Color whiteColor = Color(0xffFFFFFF);
  static const Color blackColor = Color(0xff000000);
  static const Color greyColor = Color(0xff83878B);
  static const Color greyColorSearch = Color(0xffF3F3F3);
  static const Color greyColor200 = Color(0xffEDF2F7);
  static const Color darkGreyColor = Color(0xff5c6267);
  static const Color lightGreyColor = Color(0xffD8D8D8);
  static const Color lightOrangeColor = Color(0xffFD7837);
  static const Color veryLightOrangeColor = Color(0xffff9765);
  static const Color darkColor = Color(0xff101820);
  static const Color secondaryColor = Color(0xff003B4A);
  static const Color lightGreenColor = Color(0xffE9F7F7);
  static const Color greenColor = Color(0xff4caf50);
  static const Color defaultColor = Color(0xff7B3673);
  static const Color scaffoldColor = Color(0xfff9faff);
  static const Color transparent = Colors.transparent;
  static const Color cyanColor = Color(0xff11998E);
  static const Color darkBlueColor = Color(0xff00535E);
  static const Color blackColor44 = Color(0xff363D44);
  static const Color darkColor34 = Color(0xff131A34);
  static const Color blueColor = Color(0xff007A8A);
  static const Color blackColor25 = Color(0xffE4E5E6);
  static const Color blueColor100 = Color(0xffE2F5F5);
  static const Color whiteColorF4 = Color(0xffECF0F4);
  static const Color blueColorBF = Color(0xff93BEBF);
  static const Color blueColorDE = Color(0xffB8DADE);
  static const Color partGreenMixColor = Color(0xff34C759);
  static const Color partPinkMixColor = Color(0xffFF383C);
  static const Color partCyanColor = Color(0xffF2F4F8);
  static const Color brownColor = Color(0xffFF9865);
  static const Color darkBrownColor = Color(0xffD65718);
  static const Color lightBlueColor = Color(0xffAFE2E3);
}